// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    var localServer;
    localServer = chrome.runtime.connect({
      name: "client"
    });
    $("#deleteAllUsers").click(function(event) {
      var conf;
      conf = confirm("Are you sure? \nThis will delete ALL saved users.");
      if (conf) {
        return localServer.postMessage({
          command: "deleteAllUsers",
          data: null
        });
      }
    });
    return localServer.onMessage.addListener(function(msg) {
      var status;
      switch (msg.command) {
        case "AllDataDeleted":
          status = $("#confirmation");
          status.html(msg.message);
          return setTimeout((function() {
            status.empty();
            return setTimeout((function() {
              return window.close();
            }), 300);
          }), 3000);
      }
    });
  });

}).call(this);
