// Generated by CoffeeScript 1.7.1
(function() {
  var htmlTemplates;

  htmlTemplates = {};

  htmlTemplates.mainElm = $("<div class='vom-main'>\n  <div class=\"vom-right\">\n    <div class='vom-userUi' id='badGuysUI'>\n      <ul class='vom-inlineList'>\n        <li>Bad Guys</li><span class='vom-separator'>-</span>\n      </ul>\n      <span class=\"badNotification\"></span>\n    </div>\n    <div class='vom-userUi' id='goodGuysUI'>\n      <ul class='vom-inlineList'>\n        <li>Good Guys</li><span class='vom-separator'>-</span>\n      </ul>\n      <span class=\"goodNotification\"></span>\n    </div>\n  </div>\n  <div class=\"vom-left\">\n    <ul class=\"vom-info\">\n      <li>Vote-O-Matic</li>\n      <li> - </li>\n      <li><a href=\"#\" id=\"vom-help\">help</a></li>\n      <li> - </li>\n      <li><a href=\"#\" id=\"vom-about\">about</a></li>\n    </ul>\n  </div>\n  <div class=\"vom-clear\"></div>\n</div>");

  htmlTemplates.userDialog = $("<div id=\"vom-userPopup\"></div>");

  htmlTemplates.messageDialog = $("<div id=\"vom-messagePopup\"></div>");

  htmlTemplates.generalDialog = $("<div id=\"vom-generalPopup\"></div>");

  htmlTemplates.helpText = "<div class=\"vom-dialog\">\n   <ul>\n     <li>Hover over a users name in a comment section or subreddit front page,\n         click the appropriate button to add them to a group.</li>\n     <li class=\"vom-dialog-dots\">...</li>\n     <li>Once selected voting will start immediately and the username will be added to the list at\n         the top of the page.</li>\n     <li class=\"vom-dialog-dots\">...</li>\n     <li>Vote-O-Matic will apply upvotes and downvotes to every user in your list when it\n         finds a matching name in a comment thread or subreddit front page.</li>\n     <li class=\"vom-dialog-dots\">...</li>\n     <li>To delete a user or visit their page hover over their name in the list, press \"delete\"\n         to remove them, and \"visit page\" to navigate to the users page.</li>\n   </ul>\n</div>";

  htmlTemplates.aboutText = "<div class=\"vom-dialog\">\n   <ul>\n     <li><a href=\"https://github.com/PaperElectron/Vote-O-Matic\">Source: Github/PaperElectron</a></li>\n     <li class=\"vom-dialog-dots\">...</li>\n     <li><a href=\"https://github.com/PaperElectron/Vote-O-Matic/blob/master/LICENCE.txt\">Licenced Under MIT public licence.</a></li>\n     <li class=\"vom-dialog-dots\">...</li>\n     <li>Copyright © 2014 James M. Bulkowski</li>\n   </ul>\n</div>";

  window.vomTemplates = htmlTemplates;

}).call(this);
