// Generated by CoffeeScript 1.7.1
(function() {
  var User;

  User = (function() {
    function User(user, voteDirection, uiElement) {
      var arr;
      arr = $(".author:contains(" + user + ")").closest(".thing").children(".midcol.unvoted").children(".arrow." + voteDirection);
      this.user = user;
      this.votes = $.makeArray(arr);
      this.count = $(".author:contains(" + user + ")").closest(".thing").children(".midcol").length;
      this.selector = $("<li class='vom-userDisplay' data-direction='" + voteDirection + "' data-username='" + user + "'><a href='/user/" + user + "'>" + user + ": " + this.count + "/" + arr.length + " </a></li>");
      this.separator = $("<span class='vom-separator'>-</span>");
      this.direction = voteDirection;
      uiElement.append(this.selector);
      uiElement.append(this.separator);
    }

    User.prototype.vote = function() {
      $(this.votes.shift()).click();
      this.selector.html("<li data-direction='" + this.direction + "' data-username='" + this.user + "'><a href='/user/" + this.user + "'>" + this.user + ": " + this.count + "/" + this.votes.length + "</a></li>");
      if (!this.votes.length) {
        return console.log("No more votes for " + this.user);
      }
    };

    return User;

  })();

  window.vomUser = User;

}).call(this);
